// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomeDocumentDataSlicesSlice = MijnFotosSlice;

/**
 * Content for home documents
 */
interface HomeDocumentData {
	/**
	 * title field in *home*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;

	/**
	 * Slice Zone field in *home*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>
	/**
	 * Meta Description field in *home*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: home.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *home*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;

	/**
	 * Meta Title field in *home*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: home.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_title: prismic.KeyTextField;
}

/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<HomeDocumentData>,
	'home',
	Lang
>;

export type AllDocumentTypes = HomeDocument;

/**
 * Primary content in *VisitekaartjeContainer → Primary*
 */
export interface MijnFotosSliceDefaultPrimary {
	/**
	 * NameTitle field in *VisitekaartjeContainer → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: mijn_fotos.primary.nameTitle
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	nameTitle: prismic.KeyTextField;

	/**
	 * profileImage field in *VisitekaartjeContainer → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: mijn_fotos.primary.profileImage
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	profileImage: prismic.ImageField<never>;

	/**
	 * experienceTitle field in *VisitekaartjeContainer → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: mijn_fotos.primary.experienceTitle
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	experienceTitle: prismic.KeyTextField;

	/**
	 * experienceContent field in *VisitekaartjeContainer → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: mijn_fotos.primary.experienceContent
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	experienceContent: prismic.KeyTextField;

	/**
	 * AboutTitle field in *VisitekaartjeContainer → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: mijn_fotos.primary.aboutTitle
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	aboutTitle: prismic.KeyTextField;

	/**
	 * AboutContent field in *VisitekaartjeContainer → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: mijn_fotos.primary.aboutContent
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	aboutContent: prismic.KeyTextField;

	/**
	 * linkName field in *VisitekaartjeContainer → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: mijn_fotos.primary.linkName
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	linkName: prismic.KeyTextField;

	/**
	 * githubPage field in *VisitekaartjeContainer → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: mijn_fotos.primary.githubPage
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	githubPage: prismic.LinkField;
}

/**
 * Default variation for VisitekaartjeContainer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MijnFotosSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<MijnFotosSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *VisitekaartjeContainer*
 */
type MijnFotosSliceVariation = MijnFotosSliceDefault;

/**
 * VisitekaartjeContainer Shared Slice
 *
 * - **API ID**: `mijn_fotos`
 * - **Description**: MijnFotos
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MijnFotosSlice = prismic.SharedSlice<'mijn_fotos', MijnFotosSliceVariation>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			HomeDocument,
			HomeDocumentData,
			HomeDocumentDataSlicesSlice,
			AllDocumentTypes,
			MijnFotosSlice,
			MijnFotosSliceDefaultPrimary,
			MijnFotosSliceVariation,
			MijnFotosSliceDefault
		};
	}
}
