// Code generated by Slice Machine. DO NOT EDIT.

import MijnFotos from './MijnFotos/index.svelte';
import RichText from './RichText/index.svelte';

export const components = {
	mijn_fotos: MijnFotos,
	rich_text: RichText
};
