// Code generated by Slice Machine. DO NOT EDIT.

import VisitekaartjeContainer from './VisitekaartjeContainer/index.svelte';
import RichText from './RichText/index.svelte';

export const components = {
	mijn_fotos: VisitekaartjeContainer,
	rich_text: RichText
};
