// Code generated by Slice Machine. DO NOT EDIT.

import Images from './Images/index.svelte';
import MijnFotos from './MijnFotos/index.svelte';
import RichText from './RichText/index.svelte';

export const components = {
	images: Images,
	mijn_fotos: MijnFotos,
	rich_text: RichText
};
